namespace: joezollo
name: windows
version: 0.1.0
readme: README.md
authors:
  - Joe Zollo <joe@zollo.net>
description: A set of Windows Modules
license:
- GPL-3.0-or-later
license_file: LICENSE
tags: []
dependencies: {}
repository: http://github.com/joezollo/ansible-collection-zollo-windows

# The URL to any online docs
documentation: https://github.com/joezollo/ansible-collection-zollo-windows/wiki
homepage: http://github.com/joezollo
issues: https://github.com/joezollo/ansible-collection-zollo-windows/issues
