---
- block:
  - name: Check DHCP Service/Role Install State
    ansible.windows.win_feature:
      name: DHCP
      state: present
      include_management_tools: yes
    register: dhcp_role

  - name: Reboot if Necessary
    ansible.windows.win_reboot:
    when: dhcp_role.reboot_required

  - block:
    - name: Add the DHCP scope
      ansible.windows.win_shell: |
        Add-DhcpServerv4Scope -Name "TestNetwork" -StartRange {{ item.start }} -EndRange {{ item.end }} -SubnetMask {{ item.subnet }}
      loop: "{{ dhcp_scope_testing }}"

    - name: Create New DHCP Leases
      community.windows.win_dhcp_lease:
        type: "{{ item.type }}"
        ip: "{{ item.ip }}"
        scope_id: "{{ iitem.scope_id }}"
        mac: "{{ item.mac }}"
        dns_hostname: "{{ item.dns_hostname }}"
        description: TestLeaseSuperAwesome
      loop: "{{ dhcp_testing_leases }}"

  - name: Run tests
    include_tasks: tests.yml

  always:
  - name: Remove the DHCP scope
    ansible.windows.win_shell: |
      Remove-DhcpServerv4Scope -ScopeId {{ dhcp_scope_id }} -Force