---
- name: Ensure AD/DNS roles are installed
  ansible.windows.win_feature:
    name:
      - AD-Domain-Services
      - DNS
    include_management_tools: true
    include_sub_features: true
    state: present

- name: Ensure domain is present
  ansible.windows.win_domain:
    create_dns_delegation: no
    database_path: C:\Windows\NTDS
    dns_domain_name: vmware.lan
    domain_mode: Win2012
    domain_netbios_name: VMW
    forest_mode: Win2012
    safe_mode_password: password123!
    sysvol_path: C:\Windows\SYSVOL
  register: domain_install

- block:
  - name: Ensure loopback address is set to DNS
    ansible.windows.win_dns_client:
      adapter_names: '*'
      ipv4_addresses: 127.0.0.1

  - name: Reboot if needed
    ansible.windows.win_reboot:
    when: domain_install.reboot_required

  - name: Run tests
    include_tasks: tests.yml

  - name: Run tests - check mode
    include_tasks: tests_checkmode.yml
